# Generated by Django 5.2.3 on 2025-06-18 12:51

import trainer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('firstName_en', models.CharField(max_length=255, null=True)),
                ('firstName_ar', models.CharField(max_length=255, null=True)),
                ('lastName', models.CharField(max_length=255)),
                ('lastName_en', models.CharField(max_length=255, null=True)),
                ('lastName_ar', models.CharField(max_length=255, null=True)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('bio_en', models.TextField(null=True)),
                ('bio_ar', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=trainer.models.upload_trainer_image, validators=[trainer.models.validate_image])),
                ('cv', models.FileField(blank=True, null=True, upload_to=trainer.models.upload_trainer_cv, validators=[trainer.models.validate_cv])),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
