# Generated by Django 5.2.3 on 2025-06-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='firstName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='lastName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
