# Generated by Django 5.2.3 on 2025-06-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_trainer_firstname_alter_trainer_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='firstName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='lastName',
            field=models.CharField(max_length=255),
        ),
    ]
